import '@testing-library/jest-dom/vitest';
import { beforeEach } from 'vitest';

// Mock the preload API that the renderer accesses via window.cs.
const noop = () => {};
const asyncNoop = async () => {};

const mockCs = {
  call: asyncNoop,
  listWorkspaces: async () => [],
  createWorkspace: async () => ({} as never),
  generateWorkspaceTitle: asyncNoop,
  archiveWorkspace: asyncNoop,
  workspaceFiles: async () => [],
  workspaceFileDiff: async () => '',
  setWorkspaceAutoYes: asyncNoop,
  regenerateAgent: asyncNoop,
  forceRegenerate: asyncNoop,
  commitWorkspace: async () => '',
  pushWorkspace: async () => '',
  updateWorkspace: async () => ({} as never),
  listCopilotSessions: async () => ({ sessions: [], skipped: 0 }),
  resumeCopilotSession: async () => ({} as never),
  startRun: asyncNoop,
  stopRun: asyncNoop,
  workspaceRunOutput: async () => ({ data: '', nextOffset: 0, running: false, exitCode: 0 }),
  attachSession: async () => ({ id: 0, ok: true, alive: true }),
  detachSession: asyncNoop,
  getHistory: async () => ({ ansi: '', altScreen: false, scrollbackLines: 0 }),
  ensureShell: async () => 'sh_mock',
  closeShell: asyncNoop,
  detectShells: async () => [],
  pickFolder: async () => null,
  getDefaultProgram: async () => 'copilot',
  openExternal: asyncNoop,
  getAppInfo: async () => ({
    version: '0.1.0',
    appName: 'hangar-desktop',
    electronVersion: '33.2.0',
    nodeVersion: '20.0.0',
    platform: 'win32',
    arch: 'x64',
    githubUrl: 'https://github.com/thirschel/Hangar',
    author: 'Hangar contributors',
  }),
  checkForUpdate: async () => ({ status: 'not-available' }),
  downloadUpdate: asyncNoop,
  installUpdate: asyncNoop,
  getSettings: async () => ({
    defaultProgram: 'copilot',
    defaultShell: 'cmd',
    autoYes: false,
    branchPrefix: '',
    workspaceDir: '',
    resumeAgentSessions: true,
    notifications: true,
    notificationSound: true,
    minimizeToTray: true,
    uiRefreshMs: 2000,
    autoUpdate: false,
    terminalProfiles: [],
    defaultTerminalProfileId: 'pwsh',
    verboseLogging: false,
    disableHardwareAcceleration: false,
    disableWindowOcclusion: true,
    disableDirectComposition: true,
    disableGpuCompositing: false,
    terminalNudge: 'native',
    terminalDiagnostics: false,
    terminalRenderer: 'dom',
    terminalRenderSelfTest: false,
  }),
  getLogPaths: async () => ({
    hostLog: 'C:\\Users\\test\\.hangar\\host.log',
    desktopLog: 'C:\\Users\\test\\.hangar\\desktop.log',
    hangarLog: 'C:\\Users\\test\\.hangar\\hangar.log',
  }),
  openLogFolder: asyncNoop,
  openLogFile: asyncNoop,
  readLog: async () => ({
    path: 'C:\\Users\\test\\.hangar\\host.log',
    content: '',
    truncated: false,
  }),
  setSettings: async () => ({} as never),
  getRenderInfo: async () => ({
    softwareCompositing: false,
    windowOcclusionDisabled: true,
    hardwareAccelerationDisabled: false,
    remoteSession: false,
    terminalNudge: 'native' as const,
    terminalDiagnostics: false,
    terminalRenderSelfTest: false,
    terminalRenderer: 'dom' as const,
  }),
  forceRepaint: asyncNoop,
  setTerminalRect: noop,
  onTerminalNudge: () => noop,
  notify: asyncNoop,
  setBadge: asyncNoop,
  listDir: async () => [],
  readFile: async () => ({ kind: 'text' as const, text: '' }),
  onData: () => noop,
  onReady: () => noop,
  onHostReady: () => noop,
  onUpdateStatus: () => noop,
  onClosed: () => noop,
  onError: () => noop,
  onFocusWorkspace: () => noop,
  onPlayNotificationSound: () => noop,
  onFirstRun: () => noop,
  completeSetup: asyncNoop,
  sendInput: noop,
  resize: noop,
  diag: noop,
  openDevTools: asyncNoop,
};

function installMockCs(): void {
  const target = typeof window !== 'undefined' ? window : globalThis;
  Object.defineProperty(target, 'cs', { value: mockCs, writable: true, configurable: true });
}

installMockCs();
beforeEach(() => {
  installMockCs();
});
