name: Lint

on:
  push:
    branches: [ main, dev ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/lint.yml'
  pull_request:
    branches: [ main, dev ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/lint.yml'

permissions: {}

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: '1.23'
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6
        with:
          version: v1.60.1
          args: --timeout=3m --out-format=line-number --fast --max-issues-per-linter=0 --max-same-issues=0
          skip-cache: false
          only-new-issues: true

      - name: Check formatting
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "The following files are not formatted correctly:"
            gofmt -l .
            echo "Fix these issues"
            gofmt -d .
            exit 1
          fi
